name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.3

      - name: Show repo and test file
        run: |
          python -V
          ls -la
          echo "--- tests dir ---"
          ls -la tests || true
          echo "--- test file content ---"
          test -f tests/test_ci.py && sed -n '1,120p' tests/test_ci.py || echo "tests/test_ci.py is missing"

      - name: Collect only this file
        run: |
          pytest --collect-only -q tests/test_ci.py -vv

      - name: Run just this file
        run: |
          pytest -vv tests/test_ci.py
