name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.3

      - name: Show env
        run: |
          python -V
          pip list
          ls -la
          ls -la tests || true

      - name: List tests without running
        run: pytest --collect-only -q || true

      - name: Run tests
        run: pytest -ra
