name: CI
on:
  push:
  pull_request:
jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Python sanity
        run: |
          python -V
          python - <<'PY'
          print("python works")
          PY
