name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.3 z3-solver==4.13.0.0 gradio==4.44.0

      - name: Compile for early syntax errors
        run: |
          python -m py_compile gradio_demo.py
          python - <<'PY'
          import glob, py_compile
          [py_compile.compile(p, doraise=True) for p in glob.glob("tests/*.py")]
          print("compiled tests ok")
          PY

      - name: Run tests
        run: pytest -ra
